### ISSUE TITLE
Include formulas in brew core

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/homebrew-tendermint#4]
This removes the need for the `tap` step.

**Comment by zramsay** [comment]
and it would remove the need for this repo ;)

we can also automate the update with this: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-version-upgrade-for-the-foo-formula

**Comment by adrianbrink** [comment]
Yeah, that's very true @zramsay . But for that we need to stabilise this.

**Comment by zramsay** [comment]
being handled by @melekes
